# Generated by Django 4.2.3 on 2023-09-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_active_user_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
