# Generated by Django 4.2.3 on 2023-08-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_staff_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Username'),
        ),
    ]
